spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: ${job.name:NONE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/Hi'
    username: root
    password: 1emdgkqrur
  sql:
    init:
      mode: never
  #      schema-locations: 'classpath:data/schema.sql'
  #      data-locations: 'classpath:data/data.sql'
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true