spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/Hi'
    username: root
    password: 1emdgkqrur
  sql:
    init:
      mode: always
      schema-locations: 'classpath:data/schema.sql'
      data-locations: 'classpath:data/data.sql'
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true